// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_command_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_command_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_command_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_command_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_command_2eproto;
namespace command {
class Command;
struct CommandDefaultTypeInternal;
extern CommandDefaultTypeInternal _Command_default_instance_;
class DeleteCommand;
struct DeleteCommandDefaultTypeInternal;
extern DeleteCommandDefaultTypeInternal _DeleteCommand_default_instance_;
class GetCommand;
struct GetCommandDefaultTypeInternal;
extern GetCommandDefaultTypeInternal _GetCommand_default_instance_;
class IncrementCommand;
struct IncrementCommandDefaultTypeInternal;
extern IncrementCommandDefaultTypeInternal _IncrementCommand_default_instance_;
class PutCommand;
struct PutCommandDefaultTypeInternal;
extern PutCommandDefaultTypeInternal _PutCommand_default_instance_;
}  // namespace command
PROTOBUF_NAMESPACE_OPEN
template<> ::command::Command* Arena::CreateMaybeMessage<::command::Command>(Arena*);
template<> ::command::DeleteCommand* Arena::CreateMaybeMessage<::command::DeleteCommand>(Arena*);
template<> ::command::GetCommand* Arena::CreateMaybeMessage<::command::GetCommand>(Arena*);
template<> ::command::IncrementCommand* Arena::CreateMaybeMessage<::command::IncrementCommand>(Arena*);
template<> ::command::PutCommand* Arena::CreateMaybeMessage<::command::PutCommand>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace command {

// ===================================================================

class Command final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:command.Command) */ {
 public:
  inline Command() : Command(nullptr) {}
  ~Command() override;
  explicit PROTOBUF_CONSTEXPR Command(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Command(const Command& from);
  Command(Command&& from) noexcept
    : Command() {
    *this = ::std::move(from);
  }

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }
  inline Command& operator=(Command&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Command& default_instance() {
    return *internal_default_instance();
  }
  enum CommandTypeCase {
    kPut = 1,
    kGet = 2,
    kDel = 3,
    kIncrement = 4,
    COMMAND_TYPE_NOT_SET = 0,
  };

  static inline const Command* internal_default_instance() {
    return reinterpret_cast<const Command*>(
               &_Command_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Command& a, Command& b) {
    a.Swap(&b);
  }
  inline void Swap(Command* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Command* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Command* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Command>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Command& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Command& from) {
    Command::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Command* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "command.Command";
  }
  protected:
  explicit Command(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPutFieldNumber = 1,
    kGetFieldNumber = 2,
    kDelFieldNumber = 3,
    kIncrementFieldNumber = 4,
  };
  // .command.PutCommand put = 1;
  bool has_put() const;
  private:
  bool _internal_has_put() const;
  public:
  void clear_put();
  const ::command::PutCommand& put() const;
  PROTOBUF_NODISCARD ::command::PutCommand* release_put();
  ::command::PutCommand* mutable_put();
  void set_allocated_put(::command::PutCommand* put);
  private:
  const ::command::PutCommand& _internal_put() const;
  ::command::PutCommand* _internal_mutable_put();
  public:
  void unsafe_arena_set_allocated_put(
      ::command::PutCommand* put);
  ::command::PutCommand* unsafe_arena_release_put();

  // .command.GetCommand get = 2;
  bool has_get() const;
  private:
  bool _internal_has_get() const;
  public:
  void clear_get();
  const ::command::GetCommand& get() const;
  PROTOBUF_NODISCARD ::command::GetCommand* release_get();
  ::command::GetCommand* mutable_get();
  void set_allocated_get(::command::GetCommand* get);
  private:
  const ::command::GetCommand& _internal_get() const;
  ::command::GetCommand* _internal_mutable_get();
  public:
  void unsafe_arena_set_allocated_get(
      ::command::GetCommand* get);
  ::command::GetCommand* unsafe_arena_release_get();

  // .command.DeleteCommand del = 3;
  bool has_del() const;
  private:
  bool _internal_has_del() const;
  public:
  void clear_del();
  const ::command::DeleteCommand& del() const;
  PROTOBUF_NODISCARD ::command::DeleteCommand* release_del();
  ::command::DeleteCommand* mutable_del();
  void set_allocated_del(::command::DeleteCommand* del);
  private:
  const ::command::DeleteCommand& _internal_del() const;
  ::command::DeleteCommand* _internal_mutable_del();
  public:
  void unsafe_arena_set_allocated_del(
      ::command::DeleteCommand* del);
  ::command::DeleteCommand* unsafe_arena_release_del();

  // .command.IncrementCommand increment = 4;
  bool has_increment() const;
  private:
  bool _internal_has_increment() const;
  public:
  void clear_increment();
  const ::command::IncrementCommand& increment() const;
  PROTOBUF_NODISCARD ::command::IncrementCommand* release_increment();
  ::command::IncrementCommand* mutable_increment();
  void set_allocated_increment(::command::IncrementCommand* increment);
  private:
  const ::command::IncrementCommand& _internal_increment() const;
  ::command::IncrementCommand* _internal_mutable_increment();
  public:
  void unsafe_arena_set_allocated_increment(
      ::command::IncrementCommand* increment);
  ::command::IncrementCommand* unsafe_arena_release_increment();

  void clear_command_type();
  CommandTypeCase command_type_case() const;
  // @@protoc_insertion_point(class_scope:command.Command)
 private:
  class _Internal;
  void set_has_put();
  void set_has_get();
  void set_has_del();
  void set_has_increment();

  inline bool has_command_type() const;
  inline void clear_has_command_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union CommandTypeUnion {
      constexpr CommandTypeUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::command::PutCommand* put_;
      ::command::GetCommand* get_;
      ::command::DeleteCommand* del_;
      ::command::IncrementCommand* increment_;
    } command_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_command_2eproto;
};
// -------------------------------------------------------------------

class PutCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:command.PutCommand) */ {
 public:
  inline PutCommand() : PutCommand(nullptr) {}
  ~PutCommand() override;
  explicit PROTOBUF_CONSTEXPR PutCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PutCommand(const PutCommand& from);
  PutCommand(PutCommand&& from) noexcept
    : PutCommand() {
    *this = ::std::move(from);
  }

  inline PutCommand& operator=(const PutCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline PutCommand& operator=(PutCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PutCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const PutCommand* internal_default_instance() {
    return reinterpret_cast<const PutCommand*>(
               &_PutCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PutCommand& a, PutCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(PutCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PutCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PutCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PutCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PutCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PutCommand& from) {
    PutCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PutCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "command.PutCommand";
  }
  protected:
  explicit PutCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // bytes key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // bytes value = 2;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:command.PutCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_command_2eproto;
};
// -------------------------------------------------------------------

class GetCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:command.GetCommand) */ {
 public:
  inline GetCommand() : GetCommand(nullptr) {}
  ~GetCommand() override;
  explicit PROTOBUF_CONSTEXPR GetCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetCommand(const GetCommand& from);
  GetCommand(GetCommand&& from) noexcept
    : GetCommand() {
    *this = ::std::move(from);
  }

  inline GetCommand& operator=(const GetCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetCommand& operator=(GetCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetCommand* internal_default_instance() {
    return reinterpret_cast<const GetCommand*>(
               &_GetCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetCommand& a, GetCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(GetCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetCommand& from) {
    GetCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "command.GetCommand";
  }
  protected:
  explicit GetCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
  };
  // bytes key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // @@protoc_insertion_point(class_scope:command.GetCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_command_2eproto;
};
// -------------------------------------------------------------------

class DeleteCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:command.DeleteCommand) */ {
 public:
  inline DeleteCommand() : DeleteCommand(nullptr) {}
  ~DeleteCommand() override;
  explicit PROTOBUF_CONSTEXPR DeleteCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DeleteCommand(const DeleteCommand& from);
  DeleteCommand(DeleteCommand&& from) noexcept
    : DeleteCommand() {
    *this = ::std::move(from);
  }

  inline DeleteCommand& operator=(const DeleteCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline DeleteCommand& operator=(DeleteCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DeleteCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const DeleteCommand* internal_default_instance() {
    return reinterpret_cast<const DeleteCommand*>(
               &_DeleteCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DeleteCommand& a, DeleteCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(DeleteCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DeleteCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DeleteCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DeleteCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DeleteCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DeleteCommand& from) {
    DeleteCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DeleteCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "command.DeleteCommand";
  }
  protected:
  explicit DeleteCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kVersionFieldNumber = 2,
  };
  // bytes key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // uint32 version = 2;
  void clear_version();
  uint32_t version() const;
  void set_version(uint32_t value);
  private:
  uint32_t _internal_version() const;
  void _internal_set_version(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:command.DeleteCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    uint32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_command_2eproto;
};
// -------------------------------------------------------------------

class IncrementCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:command.IncrementCommand) */ {
 public:
  inline IncrementCommand() : IncrementCommand(nullptr) {}
  ~IncrementCommand() override;
  explicit PROTOBUF_CONSTEXPR IncrementCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IncrementCommand(const IncrementCommand& from);
  IncrementCommand(IncrementCommand&& from) noexcept
    : IncrementCommand() {
    *this = ::std::move(from);
  }

  inline IncrementCommand& operator=(const IncrementCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline IncrementCommand& operator=(IncrementCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IncrementCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const IncrementCommand* internal_default_instance() {
    return reinterpret_cast<const IncrementCommand*>(
               &_IncrementCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(IncrementCommand& a, IncrementCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(IncrementCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IncrementCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IncrementCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IncrementCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IncrementCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IncrementCommand& from) {
    IncrementCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IncrementCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "command.IncrementCommand";
  }
  protected:
  explicit IncrementCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kDeltaFieldNumber = 2,
  };
  // bytes key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // int64 delta = 2;
  void clear_delta();
  int64_t delta() const;
  void set_delta(int64_t value);
  private:
  int64_t _internal_delta() const;
  void _internal_set_delta(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:command.IncrementCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    int64_t delta_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_command_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Command

// .command.PutCommand put = 1;
inline bool Command::_internal_has_put() const {
  return command_type_case() == kPut;
}
inline bool Command::has_put() const {
  return _internal_has_put();
}
inline void Command::set_has_put() {
  _impl_._oneof_case_[0] = kPut;
}
inline void Command::clear_put() {
  if (_internal_has_put()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.command_type_.put_;
    }
    clear_has_command_type();
  }
}
inline ::command::PutCommand* Command::release_put() {
  // @@protoc_insertion_point(field_release:command.Command.put)
  if (_internal_has_put()) {
    clear_has_command_type();
    ::command::PutCommand* temp = _impl_.command_type_.put_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.command_type_.put_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::command::PutCommand& Command::_internal_put() const {
  return _internal_has_put()
      ? *_impl_.command_type_.put_
      : reinterpret_cast< ::command::PutCommand&>(::command::_PutCommand_default_instance_);
}
inline const ::command::PutCommand& Command::put() const {
  // @@protoc_insertion_point(field_get:command.Command.put)
  return _internal_put();
}
inline ::command::PutCommand* Command::unsafe_arena_release_put() {
  // @@protoc_insertion_point(field_unsafe_arena_release:command.Command.put)
  if (_internal_has_put()) {
    clear_has_command_type();
    ::command::PutCommand* temp = _impl_.command_type_.put_;
    _impl_.command_type_.put_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Command::unsafe_arena_set_allocated_put(::command::PutCommand* put) {
  clear_command_type();
  if (put) {
    set_has_put();
    _impl_.command_type_.put_ = put;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:command.Command.put)
}
inline ::command::PutCommand* Command::_internal_mutable_put() {
  if (!_internal_has_put()) {
    clear_command_type();
    set_has_put();
    _impl_.command_type_.put_ = CreateMaybeMessage< ::command::PutCommand >(GetArenaForAllocation());
  }
  return _impl_.command_type_.put_;
}
inline ::command::PutCommand* Command::mutable_put() {
  ::command::PutCommand* _msg = _internal_mutable_put();
  // @@protoc_insertion_point(field_mutable:command.Command.put)
  return _msg;
}

// .command.GetCommand get = 2;
inline bool Command::_internal_has_get() const {
  return command_type_case() == kGet;
}
inline bool Command::has_get() const {
  return _internal_has_get();
}
inline void Command::set_has_get() {
  _impl_._oneof_case_[0] = kGet;
}
inline void Command::clear_get() {
  if (_internal_has_get()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.command_type_.get_;
    }
    clear_has_command_type();
  }
}
inline ::command::GetCommand* Command::release_get() {
  // @@protoc_insertion_point(field_release:command.Command.get)
  if (_internal_has_get()) {
    clear_has_command_type();
    ::command::GetCommand* temp = _impl_.command_type_.get_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.command_type_.get_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::command::GetCommand& Command::_internal_get() const {
  return _internal_has_get()
      ? *_impl_.command_type_.get_
      : reinterpret_cast< ::command::GetCommand&>(::command::_GetCommand_default_instance_);
}
inline const ::command::GetCommand& Command::get() const {
  // @@protoc_insertion_point(field_get:command.Command.get)
  return _internal_get();
}
inline ::command::GetCommand* Command::unsafe_arena_release_get() {
  // @@protoc_insertion_point(field_unsafe_arena_release:command.Command.get)
  if (_internal_has_get()) {
    clear_has_command_type();
    ::command::GetCommand* temp = _impl_.command_type_.get_;
    _impl_.command_type_.get_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Command::unsafe_arena_set_allocated_get(::command::GetCommand* get) {
  clear_command_type();
  if (get) {
    set_has_get();
    _impl_.command_type_.get_ = get;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:command.Command.get)
}
inline ::command::GetCommand* Command::_internal_mutable_get() {
  if (!_internal_has_get()) {
    clear_command_type();
    set_has_get();
    _impl_.command_type_.get_ = CreateMaybeMessage< ::command::GetCommand >(GetArenaForAllocation());
  }
  return _impl_.command_type_.get_;
}
inline ::command::GetCommand* Command::mutable_get() {
  ::command::GetCommand* _msg = _internal_mutable_get();
  // @@protoc_insertion_point(field_mutable:command.Command.get)
  return _msg;
}

// .command.DeleteCommand del = 3;
inline bool Command::_internal_has_del() const {
  return command_type_case() == kDel;
}
inline bool Command::has_del() const {
  return _internal_has_del();
}
inline void Command::set_has_del() {
  _impl_._oneof_case_[0] = kDel;
}
inline void Command::clear_del() {
  if (_internal_has_del()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.command_type_.del_;
    }
    clear_has_command_type();
  }
}
inline ::command::DeleteCommand* Command::release_del() {
  // @@protoc_insertion_point(field_release:command.Command.del)
  if (_internal_has_del()) {
    clear_has_command_type();
    ::command::DeleteCommand* temp = _impl_.command_type_.del_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.command_type_.del_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::command::DeleteCommand& Command::_internal_del() const {
  return _internal_has_del()
      ? *_impl_.command_type_.del_
      : reinterpret_cast< ::command::DeleteCommand&>(::command::_DeleteCommand_default_instance_);
}
inline const ::command::DeleteCommand& Command::del() const {
  // @@protoc_insertion_point(field_get:command.Command.del)
  return _internal_del();
}
inline ::command::DeleteCommand* Command::unsafe_arena_release_del() {
  // @@protoc_insertion_point(field_unsafe_arena_release:command.Command.del)
  if (_internal_has_del()) {
    clear_has_command_type();
    ::command::DeleteCommand* temp = _impl_.command_type_.del_;
    _impl_.command_type_.del_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Command::unsafe_arena_set_allocated_del(::command::DeleteCommand* del) {
  clear_command_type();
  if (del) {
    set_has_del();
    _impl_.command_type_.del_ = del;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:command.Command.del)
}
inline ::command::DeleteCommand* Command::_internal_mutable_del() {
  if (!_internal_has_del()) {
    clear_command_type();
    set_has_del();
    _impl_.command_type_.del_ = CreateMaybeMessage< ::command::DeleteCommand >(GetArenaForAllocation());
  }
  return _impl_.command_type_.del_;
}
inline ::command::DeleteCommand* Command::mutable_del() {
  ::command::DeleteCommand* _msg = _internal_mutable_del();
  // @@protoc_insertion_point(field_mutable:command.Command.del)
  return _msg;
}

// .command.IncrementCommand increment = 4;
inline bool Command::_internal_has_increment() const {
  return command_type_case() == kIncrement;
}
inline bool Command::has_increment() const {
  return _internal_has_increment();
}
inline void Command::set_has_increment() {
  _impl_._oneof_case_[0] = kIncrement;
}
inline void Command::clear_increment() {
  if (_internal_has_increment()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.command_type_.increment_;
    }
    clear_has_command_type();
  }
}
inline ::command::IncrementCommand* Command::release_increment() {
  // @@protoc_insertion_point(field_release:command.Command.increment)
  if (_internal_has_increment()) {
    clear_has_command_type();
    ::command::IncrementCommand* temp = _impl_.command_type_.increment_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.command_type_.increment_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::command::IncrementCommand& Command::_internal_increment() const {
  return _internal_has_increment()
      ? *_impl_.command_type_.increment_
      : reinterpret_cast< ::command::IncrementCommand&>(::command::_IncrementCommand_default_instance_);
}
inline const ::command::IncrementCommand& Command::increment() const {
  // @@protoc_insertion_point(field_get:command.Command.increment)
  return _internal_increment();
}
inline ::command::IncrementCommand* Command::unsafe_arena_release_increment() {
  // @@protoc_insertion_point(field_unsafe_arena_release:command.Command.increment)
  if (_internal_has_increment()) {
    clear_has_command_type();
    ::command::IncrementCommand* temp = _impl_.command_type_.increment_;
    _impl_.command_type_.increment_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Command::unsafe_arena_set_allocated_increment(::command::IncrementCommand* increment) {
  clear_command_type();
  if (increment) {
    set_has_increment();
    _impl_.command_type_.increment_ = increment;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:command.Command.increment)
}
inline ::command::IncrementCommand* Command::_internal_mutable_increment() {
  if (!_internal_has_increment()) {
    clear_command_type();
    set_has_increment();
    _impl_.command_type_.increment_ = CreateMaybeMessage< ::command::IncrementCommand >(GetArenaForAllocation());
  }
  return _impl_.command_type_.increment_;
}
inline ::command::IncrementCommand* Command::mutable_increment() {
  ::command::IncrementCommand* _msg = _internal_mutable_increment();
  // @@protoc_insertion_point(field_mutable:command.Command.increment)
  return _msg;
}

inline bool Command::has_command_type() const {
  return command_type_case() != COMMAND_TYPE_NOT_SET;
}
inline void Command::clear_has_command_type() {
  _impl_._oneof_case_[0] = COMMAND_TYPE_NOT_SET;
}
inline Command::CommandTypeCase Command::command_type_case() const {
  return Command::CommandTypeCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// PutCommand

// bytes key = 1;
inline void PutCommand::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& PutCommand::key() const {
  // @@protoc_insertion_point(field_get:command.PutCommand.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PutCommand::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:command.PutCommand.key)
}
inline std::string* PutCommand::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:command.PutCommand.key)
  return _s;
}
inline const std::string& PutCommand::_internal_key() const {
  return _impl_.key_.Get();
}
inline void PutCommand::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* PutCommand::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* PutCommand::release_key() {
  // @@protoc_insertion_point(field_release:command.PutCommand.key)
  return _impl_.key_.Release();
}
inline void PutCommand::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:command.PutCommand.key)
}

// bytes value = 2;
inline void PutCommand::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& PutCommand::value() const {
  // @@protoc_insertion_point(field_get:command.PutCommand.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PutCommand::set_value(ArgT0&& arg0, ArgT... args) {
 
 _impl_.value_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:command.PutCommand.value)
}
inline std::string* PutCommand::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:command.PutCommand.value)
  return _s;
}
inline const std::string& PutCommand::_internal_value() const {
  return _impl_.value_.Get();
}
inline void PutCommand::_internal_set_value(const std::string& value) {
  
  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* PutCommand::_internal_mutable_value() {
  
  return _impl_.value_.Mutable(GetArenaForAllocation());
}
inline std::string* PutCommand::release_value() {
  // @@protoc_insertion_point(field_release:command.PutCommand.value)
  return _impl_.value_.Release();
}
inline void PutCommand::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:command.PutCommand.value)
}

// -------------------------------------------------------------------

// GetCommand

// bytes key = 1;
inline void GetCommand::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& GetCommand::key() const {
  // @@protoc_insertion_point(field_get:command.GetCommand.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetCommand::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:command.GetCommand.key)
}
inline std::string* GetCommand::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:command.GetCommand.key)
  return _s;
}
inline const std::string& GetCommand::_internal_key() const {
  return _impl_.key_.Get();
}
inline void GetCommand::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* GetCommand::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* GetCommand::release_key() {
  // @@protoc_insertion_point(field_release:command.GetCommand.key)
  return _impl_.key_.Release();
}
inline void GetCommand::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:command.GetCommand.key)
}

// -------------------------------------------------------------------

// DeleteCommand

// bytes key = 1;
inline void DeleteCommand::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& DeleteCommand::key() const {
  // @@protoc_insertion_point(field_get:command.DeleteCommand.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DeleteCommand::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:command.DeleteCommand.key)
}
inline std::string* DeleteCommand::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:command.DeleteCommand.key)
  return _s;
}
inline const std::string& DeleteCommand::_internal_key() const {
  return _impl_.key_.Get();
}
inline void DeleteCommand::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* DeleteCommand::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* DeleteCommand::release_key() {
  // @@protoc_insertion_point(field_release:command.DeleteCommand.key)
  return _impl_.key_.Release();
}
inline void DeleteCommand::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:command.DeleteCommand.key)
}

// uint32 version = 2;
inline void DeleteCommand::clear_version() {
  _impl_.version_ = 0u;
}
inline uint32_t DeleteCommand::_internal_version() const {
  return _impl_.version_;
}
inline uint32_t DeleteCommand::version() const {
  // @@protoc_insertion_point(field_get:command.DeleteCommand.version)
  return _internal_version();
}
inline void DeleteCommand::_internal_set_version(uint32_t value) {
  
  _impl_.version_ = value;
}
inline void DeleteCommand::set_version(uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:command.DeleteCommand.version)
}

// -------------------------------------------------------------------

// IncrementCommand

// bytes key = 1;
inline void IncrementCommand::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& IncrementCommand::key() const {
  // @@protoc_insertion_point(field_get:command.IncrementCommand.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void IncrementCommand::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:command.IncrementCommand.key)
}
inline std::string* IncrementCommand::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:command.IncrementCommand.key)
  return _s;
}
inline const std::string& IncrementCommand::_internal_key() const {
  return _impl_.key_.Get();
}
inline void IncrementCommand::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* IncrementCommand::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* IncrementCommand::release_key() {
  // @@protoc_insertion_point(field_release:command.IncrementCommand.key)
  return _impl_.key_.Release();
}
inline void IncrementCommand::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:command.IncrementCommand.key)
}

// int64 delta = 2;
inline void IncrementCommand::clear_delta() {
  _impl_.delta_ = int64_t{0};
}
inline int64_t IncrementCommand::_internal_delta() const {
  return _impl_.delta_;
}
inline int64_t IncrementCommand::delta() const {
  // @@protoc_insertion_point(field_get:command.IncrementCommand.delta)
  return _internal_delta();
}
inline void IncrementCommand::_internal_set_delta(int64_t value) {
  
  _impl_.delta_ = value;
}
inline void IncrementCommand::set_delta(int64_t value) {
  _internal_set_delta(value);
  // @@protoc_insertion_point(field_set:command.IncrementCommand.delta)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace command

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_command_2eproto
